[package]
name = "babel"
version = "0.1.0"
authors = ["Zagdrath <zagdrath@member.fsf.org>"]
readme = "README.md"
license = "GPL-3.0"
edition = "2021"

[lib]
name = "babel"
path = "src/lib.rs"

[[bin]]
name = "babel"
path = "src/main.rs"

[dependencies]
num = "0.4.0"
rand = "0.8.4"
clap = "3.0.14"
